import { useEffect, useState } from 'react';
import Link from 'next/link';

export default function Sprint(){
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState('');
  const [day,setDay]=useState(null);
  const [tips,setTips]=useState([]);
  const [reflection,setReflection]=useState('');
  const [rating,setRating]=useState(0);
  const [aiEnabled, setAiEnabled] = useState(false);

  useEffect(()=>{
    setAiEnabled(Boolean(localStorage.getItem('ss_ai_passcode')));
    load();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);

  async function load(){
    setLoading(true); setError('');
    try{
      const pass = localStorage.getItem('ss_ai_passcode') || '';
      const res = await fetch('/api/generate-sprint', {
        method:'POST',
        headers:{
          'Content-Type':'application/json',
          'x-ss-ai-passcode': pass
        },
        body: JSON.stringify({ profile:{}, history:[] }) // can wire real profile later
      });
      const data = await res.json();
      setDay(data.day); setTips(data.tips||[]);
    }catch(e){ console.error(e); setError('Could not load today\'s sprint.'); }
    finally{ setLoading(false); }
  }

  function saveAI(){
    const code = prompt('Enter AI Dev Passcode');
    if (!code) return;
    localStorage.setItem('ss_ai_passcode', code);
    setAiEnabled(true);
    load();
  }

  function clearAI(){
    localStorage.removeItem('ss_ai_passcode');
    setAiEnabled(false);
    load();
  }

  return (
    <main style={{maxWidth:900, margin:'0 auto', padding:'24px', fontFamily:'system-ui'}}>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>
        <h1>Today&apos;s Sprint</h1>
        <div style={{display:'flex', gap:12, alignItems:'center'}}>
          <small style={{opacity:.7}}>
            AI: {aiEnabled ? 'ON (dev)' : 'OFF (mock)'}
          </small>
          {!aiEnabled
            ? <button onClick={saveAI} style={{padding:'6px 10px'}}>Enable AI</button>
            : <button onClick={clearAI} style={{padding:'6px 10px'}}>Disable AI</button>
          }
          <Link href="/dashboard">Back to Dashboard</Link>
        </div>
      </div>

      {error && <div style={{padding:12, border:'1px solid #ddd', borderRadius:8, margin:'12px 0'}}>Note: {error}</div>}
      {loading && <div style={{padding:12}}>Loading…</div>}

      {day && (
        <div style={{display:'grid', gap:16, gridTemplateColumns:'2fr 1fr'}}>
          <div style={{border:'1px solid #ddd', borderRadius:12, padding:16}}>
            <div style={{opacity:.7, fontSize:12}}>Sprint</div>
            <h3 style={{marginTop:8}}>{day.title}</h3>
            <p style={{opacity:.7, marginTop:8}}>{day.knowledge}</p>

            <div style={{marginTop:12}}>
              <b>Task</b>
              <p style={{marginTop:6}}>{day.task}</p>
            </div>

            <div style={{marginTop:12}}>
              <b>Reflection</b>
              <p style={{opacity:.7, marginTop:6}}>{day.reflection}</p>
              <textarea rows="3" style={{width:'100%'}} value={reflection} onChange={e=>setReflection(e.target.value)} />
              <div style={{display:'flex', alignItems:'center', gap:8, marginTop:8}}>
                <span style={{opacity:.7}}>How useful?</span>
                {[1,2,3,4,5].map(n=> (
                  <button key={n} onClick={()=>setRating(n)} style={{padding:'6px 10px', borderRadius:999, border: rating===n?'2px solid #0ea5e9':'1px solid #ddd', background:'#fff'}}>
                    {n}
                  </button>
                ))}
              </div>
              <div style={{textAlign:'right', marginTop:12}}>
                <button onClick={()=>alert('Saved (mock)!')} style={{padding:'10px 14px', border:'0', borderRadius:8, background:'#ff7a1a'}}>Save progress</button>
              </div>
            </div>
          </div>

          <aside style={{border:'1px solid #ddd', borderRadius:12, padding:16}}>
            <b>Tips</b>
            <ul style={{marginTop:8, paddingLeft:18}}>
              {(tips||[]).map((t,i)=> <li key={i} style={{opacity:.8, margin:'6px 0'}}>{t}</li>)}
            </ul>
            <div style={{opacity:.7, fontSize:12, marginTop:12}}>
              {aiEnabled
                ? 'AI mode (dev): content is generated by the model.'
                : 'Mock mode: demo content for testing without API costs.'}
            </div>
          </aside>
        </div>
      )}
    </main>
  );
}  function saveAI(){
    const code = prompt('Enter AI Dev Passcode');
    if (!code) return;
    localStorage.setItem('ss_ai_passcode', code);
    setAiEnabled(true);
    load();
  }

  function clearAI(){
    localStorage.removeItem('ss_ai_passcode');
    setAiEnabled(false);
    load();
  }

  return (
    <main style={{maxWidth:900, margin:'0 auto', padding:'24px', fontFamily:'system-ui'}}>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>
        <h1>Today&apos;s Sprint</h1>
        <div style={{display:'flex', gap:12, alignItems:'center'}}>
          <small style={{opacity:.7}}>
            AI: {aiEnabled ? 'ON (dev)' : 'OFF (mock)'}
          </small>
          {!aiEnabled
            ? <button onClick={saveAI} style={{padding:'6px 10px'}}>Enable AI</button>
            : <button onClick={clearAI} style={{padding:'6px 10px'}}>Disable AI</button>
          }
          <Link href="/dashboard">Back to Dashboard</Link>
        </div>
      </div>

      {error && <div style={{padding:12, border:'1px solid #ddd', borderRadius:8, margin:'12px 0'}}>Note: {error}</div>}
      {loading && <div style={{padding:12}}>Loading…</div>}

      {day && (
        <div style={{display:'grid', gap:16, gridTemplateColumns:'2fr 1fr'}}>
          <div style={{border:'1px solid #ddd', borderRadius:12, padding:16}}>
            <div style={{opacity:.7, fontSize:12}}>Sprint</div>
            <h3 style={{marginTop:8}}>{day.title}</h3>
            <p style={{opacity:.7, marginTop:8}}>{day.knowledge}</p>

            <div style={{marginTop:12}}>
              <b>Task</b>
              <p style={{marginTop:6}}>{day.task}</p>
            </div>

            <div style={{marginTop:12}}>
              <b>Reflection</b>
              <p style={{opacity:.7, marginTop:6}}>{day.reflection}</p>
              <textarea rows="3" style={{width:'100%'}} value={reflection} onChange={e=>setReflection(e.target.value)} />
              <div style={{display:'flex', alignItems:'center', gap:8, marginTop:8}}>
                <span style={{opacity:.7}}>How useful?</span>
                {[1,2,3,4,5].map(n=> (
                  <button key={n} onClick={()=>setRating(n)} style={{padding:'6px 10px', borderRadius:999, border: rating===n?'2px solid #0ea5e9':'1px solid #ddd', background:'#fff'}}>
                    {n}
                  </button>
                ))}
              </div>
              <div style={{textAlign:'right', marginTop
